/*
http://www.cgsoso.com/forum-211-1.html

CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！

CGSOSO 主打游戏开发，影视设计等CG资源素材。

插件如若商用，请务必官网购买！

daily assets update for try.

U should buy the asset from home store if u use it in your project!
*/

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEReadSceneItemKeys
    {
        public static string ReadScene_test_data = "test_data";
        public static string ReadSceneUnityTypes_unity_types_data = "unity_types_data";
        public static string ReadSceneCustom_custom_1 = "custom_1";
        public static string ReadSceneCustom_custom_2 = "custom_2";
        public static string ReadSceneCustom_custom_3 = "custom_3";
    }
}
