/*
http://www.cgsoso.com/forum-211-1.html

CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！

CGSOSO 主打游戏开发，影视设计等CG资源素材。

插件如若商用，请务必官网购买！

daily assets update for try.

U should buy the asset from home store if u use it in your project!
*/

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDESetSceneItemKeys
    {
        public static string SetSingle_single_data = "single_data";
        public static string SetCustom_custom_data_1 = "custom_data_1";
        public static string SetCustom_custom_data_2 = "custom_data_2";
        public static string SetCustom_custom_data_3 = "custom_data_3";
        public static string SetList_list_data = "list_data";
        public static string SetTwoDList_twod_list_data = "twod_list_data";
    }
}
